application:
  title: 神州物流电商平台
  version: v2.21.0
spring:
  mvc:
    static-path-pattern: /static/**
    servlet:
      load-on-startup: 1
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/shenzhoulogistics?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
    #数据库连接池配置
    hikari:
      idle-timeout: 60000
      maximum-pool-size: 30
      minimum-idle: 10
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    locale: zh_CN
    generator:
      write-numbers-as-strings: true
      write-bigdecimal-as-plain: true
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB

  mail:
    host: smtp.qq.com #qq邮箱smtp服务器地址
    port: 587
    protocol: smtp #邮件协议
    default-encoding: UTF-8 #编码字符集
    #发件人
    username: 1625987873@qq.com
    #授权码
    password: mpvxilsuregsfbcc
    #邮件服务超时时间配置
    properties:
      mail:
        debug: true #开启debug模式会完整打印邮件发送过程的日志
        smtp:
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000
  redis:
    port: 6379
    host: 127.0.0.1
  web:
    resources:
      static-locations: classpath:/static/,classpath:/templates/
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
  mapper-locations: classpath:/mapper/*.xml
  #设置实体类的自增主键
  global-config:
    db-config:
      id-type: auto
      #全局逻辑删除配置
      logic-delete-value: 1
      logic-not-delete-value: 0
#      logic-delete-field: is_delete
server:
  port: 8888

#打印sql日志
logging:
  level:
    com.shenzhou.logistics: debug

#file:
#  # 服务器上的地址 localhost:8080/uploadImages
#  staticAccessPath: /uploadImages/
#  # 本地路径 /uploadImages
#  uploadFolder: /uploadImages/

alipay:
  app_id: 2021000119666435
  private_key: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCKk5NDwhEvgOugiG8GHzvs5YiSb+xKGXhjCh6K5Ku4nUZFQ/Jrk0S2eMZ2BnEo/YyLlLtlslLj4cZ8ei8HYQdmewKIQ51dlPtmKYH/D994pENp0CpYLgLa8fSjA1gIfRieznyS8+fmzagilR8gAgXx+FRFB7CMQI0JfZxIxr4+LF/FgzmK0fCHTPwESigfGwCVcIjrr+CyHCDNNCXjwY4nC52L+TBpddqlKAIZZIZGAvACyhQLs98nPK02BeudJ8eDHLfG5cKWYvYW0A6SQusqtlE73Y/vf10tfJ5Sg3GZTAgAkPEuP0Kd/6sZ5mhsJ956ktYWYTZ3qCP0+HO18HJrAgMBAAECggEAaEEYZLynIz7xhke+hzOOaO5SriDH+wNof9JIIiRhULX5/PhedDJKWqFIZdj432bJiuVtitf65nigVFuz7/A+mgnnYM7FoHcKH9UQeOzfKisikIPMp6SN/1xSuSU14MUEdc1RCVm4WPrWCJZ54SHEiUNTWs+rMgkKUl6O6m2jCLBMI05cs5PyOJup+LrVpWHKFySz0atYJHM5wJw4rSR8sROmkISV2uIH18JsM2zc1BNsTEA5O8lmT/E20cqg2sT0tBuGtHqES7EXmy4pSbmGY0V2LnGRc6XXKuFlNY13HfuobLeWVzZDP6N10lW4OyYjib8I0S1LUnpFJxhaJ/w4iQKBgQDB4UctdsyGOQPeNoz6NxjOlhSGgz1GaffQ4GedQzm2xuj1pFp5zK267oIdy6poSDWPAbs9GVZy7OQPTaIwHcrU2yrDJLGvbxCfrapKQC9MqNwnhaf2Isb6Tb/zLjrlRqr5df9zTra3VxpvWS7K/VJBLcGaIRVYi7lKOY/bvheb7QKBgQC2+htI1634QcM/tN1CgfhCnjRfYIiw7l4G/yH1gUiGDYVduSzbgsEEaK+p5yJz2CMO5ZazXrOUxZT2I2gbJpvtLDrmwUGzQ3S77+Fg3CcsG/OQ3Xf7tRQrUGInJt2XU+2noBRVh/Ld79MBqfJfMJwKQ3k//Hiq45IO1fAc+WhstwKBgEI9bKsc1p3ZJvgp3Rqz7lbOse6PMkU3eUK1GNGDIVnQNdGPOJY6lvSx/mSdq/f7C8lzRvyGBqI3S2frF0mnNCBrTP3lMIwGv0A+/lpl+YMQgj9Ci/MtSJxGKhm0psyky091wDQuJYEYUmDOsI0L5al9L5MwUHGzMzgn2H20Qa61AoGARlI62DTjzGxhwIMfIedXZSruD9XG0tDZXDEDeRn1qGdb4RhAsCBBVBNzp4WIDSN83cXItCjqNXv18t7KrNyawnzkKjkNqfp7y5q2cIZLm70mT39+FEOUe80J2+go83ay+GAiUHjOExOPca1B0+mXnq4t1DSQn4SUZpU8EbactmMCgYEAlT0kYHKw+uc3dllFwrTpaLWNLfGjUERUHiRcDSExKYLb0frVFqxetxtFadezfHcB2T3ycOaHvvpMsdn+mbnke3Y0WaVOtXXbW+bf5KTMOix+mxQUafbbVnPp7QEdW/sgrX0KOv2EJ1uwP/Px+Cq9NAkLKamMPt191OJ9p5mWzbc=
  public_key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA9cKAEOXdG9FyjJOG+exmWNwtfoOH/inruX4AGojLzwrLpNgWJCauKJh9XFn9HifKlF/Mg9ubz1rdl0QJLkWsK3RMw2ShdMagl1QaRosE6S5GWfOGPtMErdAA1llFI5+gt+dvcj6B6xwPuIg6SUIdtXFgyuLOmYNkjL+agPvjEPgW1iQxtz9x1W8IwcyVNKvNikHEatTjN85EZv9iuOtO+ostPUJ8iO5nmzv+xEEki5Yy0sv8FfK+DygFnBm9aPQ2oa7YVggaLMs2u7cxYSeVbYaPi7U0z24WyBw0Qhaj81ZT1DXYumLjpjpou4oEkd4jTn/7IriOlI+IjJSxA8hgqwIDAQAB
  notify_url: https://andretech.cn/api/alipay/notifyUrl
  return_url: https://andretech.cn/#/webapp/userspace/orderQuery
  sign_type: RSA2
  charset: utf-8
  gatewayUrl: https://openapi.alipaydev.com/gateway.do
  log_path: C:/tmp/
